```{r child_100_data_wrangling, echo=FALSE}
  knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
##########################################################################################################################################
# Analysis Part 100 
##########################################################################################################################################

##########################################################################################################################################
# 10d for high-level Map graphs
##########################################################################################################################################
  
  ##########################################################################################################################################
  # Map Datasets
  world_map <- map_data("world") %>%
      filter(region == "Canada" | region == "Mexico" | region == "USA")
  
  us_map <- map_data("state")
  
  ##########################################################################################################################################
  # DATA: Border Crossing Dataset (aggregated to proper Grain)  
  data_10c_core <- data_00_base_mod %>%
    filter(measure_summary == "Personal Vehicles" | measure_summary == "Pedestrians" | measure_summary == "Trucks" | measure_summary == "Buses" | measure_summary =="Trains") %>% 
    filter(Year == "2023") %>%
    dplyr::select(Year, Border_Code, Latitude, Longitude, Port.Name, State, Value) %>%
    group_by(Year, Border_Code, Latitude, Longitude, Port.Name, State) %>%
    summarise(crossings = sum(Value), record_cnt = n(), .groups = 'keep') %>%
    mutate(size_class = cut(crossings,breaks=c(0,200000,400000,600000,1400000,Inf), labels=c("< 200K", "200K-400K", "400K-600K", "600K-1.4M", "1.4M-2.5M" ))) %>% 
    mutate(shape_class = cut(crossings,breaks=c(0,200000,400000,600000,1400000,Inf), labels=c(4,3,21,22,23))) %>%
    arrange(Border_Code, - crossings)  
  ##########################################################################################################################################
  # GRAPH: Border Crossing Dataset (aggregated to proper Grain)  
  suppressWarnings({ 
    gg_00a_map_intl_borders <- ggplot() + 
      geom_polygon(data=world_map, aes(x=long, y=lat, fill=region, group=group), color = "white", alpha = .9) + 
      geom_polygon(data=us_map, aes(x=long, y=lat, group=group), color = "white", alpha = 0, linewidth = .1) + 
      geom_point(data=data_10c_core, aes(x=Longitude, y=Latitude, size = size_class, stroke = .75), shape = 21, color = "black", fill="gray90") + 
      guides(fill="none") + 
      labs(title="North American Internationial Borders",
           subtitle='US International Borders and Ports of Entry',
           # caption=c('Source: Bureau of Transportation Statistics'),
           size = "2023 Inbound Crossings") +
        theme_minimal() +
        theme(
          axis.text.y = element_blank(),
          axis.title.y = element_blank(),
          axis.text.x = element_blank(),
          axis.title.x = element_blank(),
          legend.position="top",
          panel.background = element_blank(),
          strip.background = element_rect(colour = "gray50", fill = "gray90"),
          panel.border = element_rect(colour = "gray50", fill = NA, size = .2), 
          panel.grid.minor.y = element_blank(),        
          panel.grid.major.y = element_blank(),        
          panel.grid.minor.x = element_blank(),        
          panel.grid.major.x = element_blank(), 
          plot.caption = element_text(hjust=0, size=11)
        ) +
      # theme_void()+
      # theme(title=element_text(face='bold'),
      #       legend.position = 'right') + 
      # ggtitle('North America') + +
        labs(
          title = "USA International Borders | Mapped",
          y = "",
          x = "",
          # y = data_10d_core_melt$measure,
          subtitle = "US Ports of Entry, size of the circle indicates volume of Border Crossings in 2023",
          caption = "Fig 1A: US Ports of Entry on Map of North America"
        ) +
      scale_colour_manual(values = cols_world) +
      coord_map(xlim = c(-160, -55), ylim = c(15, 68))    
  })

##########################################################################################################################################
# Facet Wrap version of the Bar Graphs
##########################################################################################################################################    

##########################################################################################################################################
# DATA: Data gathering for 10d_core that will cover several high-level graphs

# Main Data Wrangling to get to the right section and grain
data_10d_core <- data_00_base_mod %>%
  filter(measure_summary == "Personal Vehicles" | measure_summary == "Pedestrians" | measure_summary == "Trucks" | measure_summary == "Buses" | measure_summary =="Trains") %>% 
  filter(Year == "2023") %>%
  dplyr::select(Year, Border_Code, State, Port.Name, Value) %>%
  group_by(Year, Border_Code) %>%
  summarise(ports_of_entry_cnt = n_distinct(Port.Name), crossings = sum(Value), states_on_border_cnt = n_distinct(State), .groups = 'keep') %>%
  mutate(border_miles = ifelse(grepl("CAN", Border_Code, fixed = TRUE), 5525, 1954)) 

# change the column order to be a little more readable (nice, but not required)
data_10d_core <- data_10d_core[,c(1,2,6,5,3,4)]

# Do some additional clean-up to the columns so we can cleanse after the column_names are melted to be rows
data_10d_core_rename <- data_10d_core
colnames(data_10d_core_rename) <- c("Year", "Border_Code", "Miles_of_Border", "States_on_Border", "Ports_of_Entry", "Border_Crossings")
data_10d_core_melt <- data_10d_core_rename %>%
  pivot_longer(!c(Year,Border_Code),names_to = "measure",values_to = "value") %>%
  mutate(measure = gsub("_"," ",measure)) %>%
  mutate(measure = factor(measure, order = TRUE, levels = c("Miles of Border", "Ports of Entry", "States on Border", "Border Crossings"))) %>%
  mutate(col_fill_color = as.factor(ifelse(grepl("CAN", Border_Code, fixed = TRUE), "#F8756D", "#33C051")))

  # Use this to create a custom discrete color scale that matches the map above
  cols_border_crossing<- c("CAN" = "#F8756D", "MEX" = "#33C051", "USA" = "#73A6FF")

##########################################################################################################################################
# GRAPH

gg_10d__facet <- ggplot(data_10d_core_melt, 
                        aes(
                          x = data_10d_core_melt$Border_Code,
                          y = value
                        )) +
  geom_col(
    #aes(fill = mode_color_code,color = Border_Code)
    # aes(fill = factor(data_10d_core_melt$col_fill_color)),
    aes(fill = factor(data_10d_core_melt$Border_Code)),
    color = "gray10",
    alpha = 1
  ) + 
  # geom_label(
  #   aes(label = scales::comma(data_10d_core_melt$value)
  #       # label = value # paste(round(crossings / 1e6, 0), "M")
  #   ),
  #   hjust = .5,
  #   vjust = -.5,
  #   fill = NA,
  #   label.size = 0
  # ) +
  geom_text(
    aes(label = scales::comma(data_10d_core_melt$value))
    ,vjust = -.8,
    ,size = 3.8
  ) + 
  # scale_fill_identity() +
  facet_wrap(vars(measure), nrow = 1, scales = "free_y")  +
  # facetted_pos_scales(
  #   y = list(
  #     vars(measure) == "Miles of Border" ~ scale_y_continuous(breaks = seq(0, 8000, by = 2000), limits= c(0,8000)),
  #     vars(measure) == "Points of Entry" ~ scale_y_continuous(breaks = seq(0, 120, by = 30), limits= c(0,120)),
  #     vars(measure) == "States on Border" ~ scale_y_continuous(breaks = seq(0, 16, by = 4), limits= c(0,16)),
  #     vars(measure) == "Border Crossings" ~ scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6), breaks = seq(0, 200000000, by = 50000000),limits= c(0,200000000))
  #   )
  theme_minimal() +
  theme(
    axis.text.y = element_text(angle = 0),
    axis.title.y = element_blank(),
    panel.background = element_blank(),
    strip.background = element_rect(colour = "gray50", fill = "gray90"),
    panel.border = element_rect(colour = "gray50", fill = NA, size = .2), 
    panel.grid.minor.y = element_blank(),        
    panel.grid.major.x = element_blank(),        
    panel.grid.minor.x = element_blank(),
    plot.caption = element_text(hjust=0, size=11)
  ) +
  scale_x_discrete(
    name = "USA Border" #"data_10d_core_melt$Border_Code,
    # labels = unit_format(unit = "M", scale = 1e-6)
  ) +
  # scale_fill_manual(values =  data_10d_core_melt$col_fill_color) + #cols_border_crossing) +
  scale_fill_manual(values = cols_border_crossing) +  
  facetted_pos_scales(
    y = list(
      measure == "Miles of Border" ~ scale_y_continuous(breaks = seq(0, 8000, by = 2000),limits= c(0,8000)),
      measure == "Ports of Entry" ~ scale_y_continuous(breaks = seq(0, 120, by = 30),limits= c(0,120)), 
      measure == "States on Border" ~ scale_y_continuous(breaks = seq(0, 16, by = 4), limits= c(0,16)) ,
      measure == "Border Crossings" ~ scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6),breaks = seq(0, 160000000, by = 40000000),limits= c(0,160000000)) 
    )
  ) +
  labs(
    title = "USA International Borders | Overview",
    y = data_10d_core_melt$measure,
    subtitle = "Border Crossings is for 2023",
    caption = "Fig 2: MEX Border has disproportionate # of Crossings"
  )    + 
  guides(fill="none")

      
```

```{r echo=FALSE, message=FALSE, warning=FALSE,}
  ##########################################################################################################################################
  # DATA: Border Crossing Dataset (aggregated to proper Grain)  
  data_10e_core <- data_00_base_mod %>%
    filter(measure_summary == "Personal Vehicles" | measure_summary == "Pedestrians" | measure_summary == "Trucks" | measure_summary == "Buses" | measure_summary =="Trains") %>% 
    filter(Year == "2023") %>%
    dplyr::select(Year, Border_Code, State, Value) %>%
    group_by(Year, Border_Code, State) %>%
    summarise(crossings = sum(Value), record_cnt = n(), .groups = 'keep') %>%
    mutate(color_class = cut(crossings,breaks=c(0,1000000, 10000000, 25000000,50000000,100000000,Inf), labels=c("< 1M", "1M-10M", "10M-25M", "25M-50M", "50M-100M", "100M+" ))) %>% 
    # mutate(shape_class = cut(crossings,breaks=c(0,200000,400000,600000,1400000,Inf), labels=c(4,3,21,22,23))) %>%
    mutate(region = tolower(State))  %>%
    arrange(Border_Code, desc(crossings),  .by_group = FALSE)


    ##########################################################################################################################################
    # DATA: 2023 CAN Border Crossings by State  
    
    data_10e_bar_can <- data_10e_core %>%
      filter(Border_Code == "CAN") %>%
      arrange(desc(crossings)) 

    ##########################################################################################################################################
    # GRAPH: 2023 CAN Border Crossings by State          
    
    gg_10e_bar_us_state_crossings_can <- ggplot(data = data_10e_bar_can) +
      geom_col(aes(
        x=reorder(State, crossings, FUN = sum),
        # reorder(iss$spray, iss$count, FUN = mean)
        y=crossings
        ),
        fill = "#F8756D",
        color = "gray50"
      ) + 
      geom_text(
        aes(
          x=reorder(State, crossings, FUN = sum)
          ,y=crossings
          ,label = paste(round(crossings / 1e6, 1), "M"))
          ,vjust = 0
          ,hjust = -.5
          ,size = 3.8
      ) +
      coord_flip() +
      theme_minimal() +
      theme(
        axis.text.y = element_text(angle = 0),
        panel.background = element_blank(),
        strip.background = element_rect(colour = "gray50", fill = "gray90"),
        panel.border = element_rect(colour = "gray50", fill = NA, size = .2), 
        panel.grid.major.y = element_blank(),
        panel.grid.minor.x = element_blank(),
        plot.caption = element_text(hjust=0, size=11)
      ) +
      scale_y_continuous(
        labels = unit_format(unit = "M", scale = 1e-6),
        breaks = seq(0, 60000000, by = 15000000),
        limits= c(0,70000000)
      ) +
      labs(title = "2023 Border Crossings from CAN by US State",
        x = "US State",
        y = "2023 Border Crossings (CAN)",
        caption="Fig 1B: 2023 Border Crossings (CAN)"
      ) 
      
      ##########################################################################################################################################
      # DATA: 2023 MEX Border Crossings by State  
      
      data_10e_bar_mex <- data_10e_core %>%
        filter(Border_Code == "MEX") %>%
        arrange(desc(crossings)) 
      
      ##########################################################################################################################################
      # GRAPH: 2023 MEX Border Crossings by State          
      
      gg_10e_bar_us_state_crossings_mex <- ggplot(data = data_10e_bar_mex) +
        geom_col(aes(
          x=reorder(State, crossings, FUN = sum),
          # reorder(iss$spray, iss$count, FUN = mean)
          y=crossings
        ),
        fill = "#33C051",
        color = "gray50"
        ) + 
        geom_text(
          aes(
            x=reorder(State, crossings, FUN = sum)
            ,y=crossings
            ,label = paste(round(crossings / 1e6, 1), "M"))
          ,vjust = 0
          ,hjust = -.5
          ,size = 3.8
        ) +
        coord_flip() +
        theme_minimal() +
        theme(
          # axis.text.y = element_text(angle = 0),
          panel.background = element_blank(),
          strip.background = element_rect(colour = "gray50", fill = "gray90"),
          panel.border = element_rect(colour = "gray50", fill = NA, size = .2), 
          panel.grid.major.y = element_blank(),
          panel.grid.minor.x = element_blank(),
          plot.caption = element_text(hjust=0, size=11)
        ) +
        scale_y_continuous(
          #name = "Inbound Border Crossings",
          labels = unit_format(unit = "M", scale = 1e-6),
          breaks = seq(0, 60000000, by = 15000000),
          limits= c(0,70000000)
        ) +
        labs(title = "2023 Border Crossings from MEX by US State",
          x = "US State",
          y = "2023 Border Crossings (MEX)",
          caption="Fig 1C: 2023 Border Crossings (MEX)"
          ) 
```      
      